### ISSUE TITLE
[Issue] [1.21] Toolkit in neoForge

### ISSUE THREAD

**Issue by Periam** [nanite/ToolKit#11]
### Minecraft Version

1.21

### Modloader

Neoforge 21.0.37

### Mod version

ToolKit-neoforge-87.0.0.jar

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[crash-2024-06-26_11.12.57-fml.txt](https://github.com/user-attachments/files/15990611/crash-2024-06-26_11.12.57-fml.txt)

### Steps to reproduce the issue

1-Install Architectury API (architectury-13.0.2-neoforge)
2-InstallTool Kit (ToolKit-neoforge-87.0.0)
3-launch the game

### Description of the issue you are having

After installing Architectury Api and tool kit mod the game does not launch.

Thread: Render thread
Stacktrace:
at TRANSFORMER/[neoforge@21.0.24-beta](mailto:neoforge@21.0.24-beta)/net.neoforged.neoforge.network.registration.NetworkRegistry.register(NetworkRegistry.java:169) ~[neoforge-21.0.24-beta-universal.jar%23184!/:?] {re:classloading}
-- MOD architectury --
Details:
Failure message: fml.modloading.errorduringevent
Failure message arg 1: net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent
Mod Version: 13.0.1
Mod Issue URL: https://github.com/shedaniel/architectury/issues
Exception message: java.lang.UnsupportedOperationException: Cannot register payload toolkit:networking_channel/574ee0fe76fa3a278654f409e92f4e3f as it is already registered.

### Information

- [X] I have provided as much information as possible

**Comment by nfox18212** [comment]
I've also encountered this exact crash on 1.20.6.  Same error message, same steps to reproduce.  
Neoforge version is 20.6.119, Architectury api is 12.1.3 and Toolkit version is 86.0.0.

crash log: 
[crash-2024-07-13_12.10.26-fml.txt](https://github.com/user-attachments/files/16202884/crash-2024-07-13_12.10.26-fml.txt)

**Comment by Periam** [comment]
No longer using the MC 1.21 version
