### ISSUE TITLE
[Issue][1.19] Currently Dies on dedicated server

### ISSUE THREAD

**Issue by Saereth** [nanite/ToolKit#3]
### Mod version

ToolKit-2.3.0-build.5+mc1.19-dev

### Forge mod loader version

41.0.16

### Repeatable?

- [X] Yes

### Link to log files

https://www.toptal.com/developers/hastebin/abamutekix.properties

### Steps to reproduce the issue

use the mod on a dedicated server, it will hang and then the server will stop. No Crash log is generated

### Description of the issue you are having

Using the mod on a dedicated server currently causes the server to fail to load. Removing the mod resolves this issue. If you want any other logs, info or testing done by me, let me know, thanks

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
https://c.mikey.pro/screenshots/2022/06/Parsec_CB08AF29-D87B-4C2F-B5F8-A5119071DF8D.png Can't replicate? The error is also really strange, do you have any mods that modify how commands work? Or maybe a mod that also adds a command called 'tk'? 

Tested in dev env with the same forge version

**Comment by Sunekaer** [comment]
17c28ec5dc2c675a2e4c3caff4a73872135e3d3c
