### ISSUE TITLE
wrong jar for 2.3.5 on curseforge?

### ISSUE THREAD

**Issue by adrianmgg** [nanite/ToolKit#5]
### Mod version

`ToolKit-2.3.5-build.9+mc1.19-dev.jar`

### Forge mod loader version

`41.1.0`

### Repeatable?

- [X] Yes

### Link to log files

(see description)

### Steps to reproduce the issue

(created a new multimc instance with mc 1.19, forge 41.1.0. added ToolKit jar and no other mods.)
1. launch the game
1. create a new singleplayer world

### Description of the issue you are having

with the 2.3.5 jar from curseforge (`ToolKit-2.3.5-build.9+mc1.19-dev.jar`), this crashes with a `NoSuchMethodError` caused by toolkit ([log](https://gist.github.com/adrianmgg/77b4f7578349659bdfd1f9e08f082f74#file-toolkit-2-3-5-build-9-mc1-19-dev-jar-log), see lines 464, 562)

i can reproduce this by building the same version of the mod from source and using `build/devlibs/ToolKit-2.3.5-build.9999+mc1.19-dev.jar` ([log](https://gist.github.com/adrianmgg/77b4f7578349659bdfd1f9e08f082f74#file-toolkit-2-3-5-build-9999-mc1-19-dev-jar-log), see lines 464, 562).

if i instead use `build/libs/ToolKit-2.3.5-build.9999+mc1.19.jar`, i get no crash ([log](https://gist.github.com/adrianmgg/77b4f7578349659bdfd1f9e08f082f74#file-toolkit-2-3-5-build-9999-mc1-19-jar-log)).

seems like the wrong jar was used for that version's curseforge release?

---

editing to add: [here's the line in the github action log where it says it uploaded the `-dev` jar](https://github.com/nanite/ToolKit/runs/7378710660?check_suite_focus=true#step:5:106). compare to the [next run](https://github.com/nanite/ToolKit/runs/7599993927?check_suite_focus=true#step:5:109) and the [previous run](https://github.com/nanite/ToolKit/runs/6865536369?check_suite_focus=true#step:5:107), which uploaded the correct jar. maybe an issue with the build/release code?

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
fixed
